[msg dress_005]
[s]Yasogami High winter[n]uniform for women.[n][e]

[msg dress_00D]
[s]Yasogami High summer[n]uniform for women.[n][e]

[msg dress_015]
[s]Simple clothes for[n]Inaba's hot summers.[n][e]

[msg dress_020]
[s]Warm clothes for[n]Inaba's cold winters.[n][e]

[msg dress_035]
[s]Rise's Bikini[n]TO CHANGE[n][e]

[msg dress_05F]
[s]Basic style for entering a[n]hot spring. Remember not to[n]let the towel into the water.[n][e]

[msg dress_085]
[s]Rise's Yukata[n]TO CHANGE[n][e]

[msg dress_095]
[s]Heavy winter clothing for the chilling winters of Inaba.[n]The pastel colors help it pop.[n][e]

[msg dress_0B5]
[s]Rise's tofu shop outfit[n]TO CHANGE[n][e]

[msg dress_0BD]
[s]A modified Yasogami High uniform for the cold winters.[n]The (insert adjective here) jacket makes for a simple yet stylish appearance.[n][e]

[msg dress_0C5]
[s]Rise's Ski Trip Outfit[n]TO CHANGE[n][e]

[msg dress_0CD]
[s]Rise's Epilogue Outfit[n]TO CHANGE[n][e]

[msg dress_0D5]
[s]Shadow Rise[n]TO CHANGE[n][e]
