[msg dress_005]
[s]Yasogami High winter[n]uniform for women.[n][e]

[msg dress_00D]
[s]Yasogami High summer[n]uniform for women.[n][e]

[msg dress_015]
[s]Simple clothes for[n]Inaba's hot summers.[n][e]

[msg dress_020]
[s]Warm clothes for[n]Inaba's cold winters.[n][e]

[msg dress_025]
[s][s]Classy Gekkoukan High[n]uniform for women.[n][e]

[msg dress_035]
[s]A flashy orange bikini [n]fit for an idol.[n][e]

[msg dress_05F]
[s]Basic style for entering a[n]hot spring. Remember not to[n]let the towel into the water.[n][e]

[msg dress_085]
[s]Customary summer festival outfit, [n]ideal for any girl who wants [n]to stand out.[n][e]

[msg dress_095]
[s]Heavy winter clothing for the [n]chilling winters of Inaba.[n]The pastel colors help it pop.[n][e]

[msg dress_0B5]
[s]Unassuming work clothes for [n]Marukyu Tofu. Its simple appearance [n]can make even idols look plain.[n][e]

[msg dress_0BD]
[s]A modified Yasogami High uniform [n]for the cold winters. The pink [n]scarf stands out.[n][e]

[msg dress_0C5]
[s]Heavy skiing clothes, [n]for staying warm on the slopes.[n][e]

[msg dress_0CD]
[s]This trendy look is the latest in [n]summer fashion! The thin clothes let [n]you stay cool while looking stylish.[n][e]

[msg dress_0D5]
[s]A revealing swimsuit born from [n]formerly repressed feelings. [n]Who made this, anyways...?[n][e]
